Feature/boosting rules
lmc-eu/matej-client-php pull request #111
Opened 2020-03-29 19:43 UTC by JakubTesarek

2020-03-31 12:06 UTC, OndraM requested changes

2020-03-31 12:06 UTC, OndraM commented on src/Model/Command/UserRecommendation.php
> +            function($boost) {return $boost->jsonSerialize(); }, $this->boosts
```suggestion
        function (Boost $boost) {
            return $boost->jsonSerialize();
        },
        $this->boosts
```

2020-03-31 12:06 UTC, OndraM commented on src/Model/Command/UserRecommendation.php
> +    protected function serializeBoosts(): array
```suggestion
    protected function getSerializedBoosts(): array
```

To make it clear from the name the method does not have sideffects.

2020-03-31 12:06 UTC, OndraM commented on tests/unit/Model/Command/BoostTest.php
> +    public function multiplierHasToBeGreaterThan0(): void
```suggestion
    public function shouldNotAllowMultiplierLessThan0(): void
```

2020-03-31 12:06 UTC, OndraM commented on tests/unit/Model/Command/BoostTest.php
> +        $boost = Boost::create('valid_to >= NOW()', -1);
```suggestion

        Boost::create('valid_to >= NOW()', -1);
```

2020-03-31 12:06 UTC, OndraM commented on README.md
> +You can further modify which items will be reccomended by providing boosting rules. Priority of items matching the
```suggestion
You can further modify which items will be recommended by providing boosting rules. Priority of items matching the
```

2020-03-31 12:06 UTC, OndraM commented on README.md
> +$reccomendation = UserRecommendation::create('user-id', 5, 'test-scenario', 1.0, 3600)
```suggestion
$recommendation = UserRecommendation::create('user-id', 5, 'test-scenario', 1.0, 3600)
```

2020-03-31 12:06 UTC, OndraM commented on README.md
> +You can further modify which items will be reccomended by providing boosting rules. Priority of items matching the
I'd move this whole added section right before "From $response, you can also access rest of the data:".

Or maybe better merge it with the example following "You can also set more granular options of the recommendation command", something like this:

```php
$recommendation = UserRecommendation::create('user-id', 5, 'test-scenario', 1.0, 3600);
$recommendation->setFilters(['for_recommendation = 1'])
    ->addBoost(Boost::create('valid_to >= NOW()', 2)) // Priority of items matching the Booster criteria will be multiplied by the value of multiplier
    ->addBoost(Boost::create('for_recommendation = 1', 3.5))
    ->setMinimalRelevance(MinimalRelevance::HIGH())
    ->enableHardRotation();

$response = $matej->request()
    ->recommendation($recommendation)
    ->send();
```

2020-04-03 16:30 UTC, JakubTesarek commented
All fixed. I'll squash on merge

2020-04-05 00:34 UTC, OndraM requested changes
I found just one glitch in readme, otherwise ✅ 

Thanks 👍

2020-04-05 00:34 UTC, OndraM commented on README.md
> +$recommendation = UserRecommendation::create('user-id', 5, 'test-scenario', 1.0, 3600)
```suggestion
$recommendation = UserRecommendation::create('user-id', 5, 'test-scenario', 1.0, 3600);
```

2020-04-06 07:29 UTC, JakubTesarek commented on src/Model/Command/UserRecommendation.php
> +    protected function serializeBoosts(): array
fixed

2020-04-09 15:16 UTC, OndraM approved these changes

2020-04-09 15:17 UTC, merged