Jt@new recommendations
lmc-eu/matej-client-php pull request #132
Opened 2020-12-03 14:14 UTC by JakubTesarek

2020-12-10 15:15 UTC, OndraM requested changes

2020-12-10 15:15 UTC, OndraM commented on CHANGELOG.md
> +- **BC BREAK** | Class `MinimalRelavance` renamed to `ItemMinimalRelevances`.
```suggestion
- **BC BREAK** | Rename class `MinimalRelavance` to `ItemMinimalRelevance`.
```
(ItemMinimalRelevance*s*)

2020-12-10 15:15 UTC, OndraM commented on CHANGELOG.md
> +- Added support for new recommendation types - `UserUserRecommendation`, `ItemUserRecommendation`, `ItemItemRecommendation`.
```suggestion
- Add support for new recommendation types - `UserUserRecommendation`, `ItemUserRecommendation`, `ItemItemRecommendation`.
```

Changelog items (after "Added", "Changed" heading etc.) should be in present tense (btw so should also commit messages).

2020-12-10 15:15 UTC, OndraM commented on CHANGELOG.md
> +- **BC BREAK** | Class `UserRecommendation` renamed to `UserItemRecommendation`.
```suggestion
- **BC BREAK** | Remove deprecated constant `FILTER_TYPE_MQL` from `UserRecommendation`.
- **BC BREAK** | Rename class `UserRecommendation` to `UserItemRecommendation`.
```

2020-12-10 15:15 UTC, OndraM commented on CHANGELOG.md
> +- **BC BREAK** | Class `Sorting` renamed to `ItemSorting`.
```suggestion
- **BC BREAK** | Rename class `Sorting` to `ItemSorting`.
```

2020-12-10 15:15 UTC, OndraM commented on README.md
> +You can also set more granular options of the recommendation command and overwrite Matej default behaviour on per-request basis.
We usually use US english in tech documentation, so `behavior` can be preserved for consistency :)

2020-12-10 15:15 UTC, OndraM commented on README.md
> +| scenario      |              `static::create`               |            ✅           |            ✅           |            ✅           |            ✅           |
```suggestion
| scenario      |              in constructor               |            ✅           |            ✅           |            ✅           |            ✅           |
```

This was a bit confusing for me, until I realized its meant the required value in constructor, right?

2020-12-10 15:15 UTC, OndraM commented on UPGRADE-4.0.md
> +described in table bellow:
```suggestion
Each recommendation type supports different parameter options. Available parameters are
described in table below:
```

2020-12-10 15:15 UTC, OndraM commented on UPGRADE-4.0.md
> +Each recommendation type supports different parameter options. Awailable parameters are
I'd rather link to the readme (you can link to specific #header), instead of duplicating this whole table below (it will be easier to maintain in case of bug, updates etc.) - users will be pointed to the most up-to-date documentation.

2020-12-10 15:15 UTC, OndraM commented on UPGRADE-4.0.md
> +    ->setRotationTime(3600);
I'd omit the last 3 lines - they are not relevant for the change, and keep just this:

```suggestion
    ->setMinimalRelevance(MinimalRelevance::LOW());
```

2020-12-10 15:15 UTC, OndraM commented on src/Model/Command/AbstractRecommendation.php
> +     */
This comment could be removed, it does not provide any additional information...

2020-12-10 15:15 UTC, OndraM commented on src/Model/Command/AbstractUserRecommendation.php
> +        if ($this->rotationRate !== null) {
```suggestion
        if ($this->rotationTime !== null) {
```

It also means this is not covered by a test 🤔

2020-12-10 15:15 UTC, OndraM commented on src/Model/Command/ItemsFilteringTrait.php
> +     * Set boosts. Removes all previously set rules.
```suggestion
     * Set boosts. Removes all previously set rules.
     *
     * @param Boost[] $boosts
```

2020-12-10 15:15 UTC, OndraM commented on src/Model/Command/ItemsFilteringTrait.php
> +        $this->boosts = $boosts;
```suggestion
        Assertion::allIsInstanceOf($boosts, Boost::class);

        $this->boosts = $boosts;
```

2020-12-10 15:15 UTC, OndraM commented on tests/integration/RequestBuilder/EventsRequestBuilderTest.php
> +    }
Why is this a method? It can be only a class constant, like

```php
    private const PROPERTIES_LIST = [
        'test_property_a',
        'test_property_b',
        'test_property_c',
    ];
```

2020-12-10 15:15 UTC, OndraM commented on tests/integration/RequestBuilder/EventsRequestBuilderTest.php
> +            usleep(1000000); # 0.1s
1000000 µs is 1 second, so it should be:

```suggestion
            usleep(100000); // 0.1s
```

2020-12-10 15:15 UTC, OndraM commented on tests/integration/RequestBuilder/EventsRequestBuilderTest.php
> +    private static function removeItemProperties(Matej $matej): void
The method is called `removeItemProperties`, while it actually also create the properties... So its maybe something like  "resetItemProperties"?

2020-12-10 15:15 UTC, OndraM commented on tests/unit/Model/Command/ItemItemRecommendationTest.php
> +        $this->assertSame(
Maybe use HEREDOC to make it easier to read:

https://www.php.net/manual/en/language.types.string.php#language.types.string.syntax.heredoc

2020-12-10 15:15 UTC, OndraM commented on tests/unit/RequestBuilder/CampaignRequestBuilderTest.php
> +        $recommendationCommand4 = ItemItemRecommendation::create('itemId2', 'scenario3')
```suggestion
        $recommendationCommand4 = ItemItemRecommendation::create('itemId2', 'scenario4')
```
(only for consistency)

2020-12-10 15:15 UTC, OndraM commented on README.md
> +You can request 4 types of recommendation from Matej. Each of them is represented by a specific recommendation command class:
```suggestion
You can request 4 types of recommendations from Matej. Each of them is represented by a specific recommendation command class:
```

2020-12-10 15:15 UTC, OndraM commented on README.md
> +Each type of recommendation command supports different customization options. See table bellow.
```suggestion
Each type of recommendation command supports different customization options. See table below.
```

2020-12-10 15:15 UTC, OndraM commented on UPGRADE-4.0.md
> +New types of recommendations can be created is similar way to `UserItemRecommendation`. For example:
```suggestion
New types of recommendations can be created in a similar way to `UserItemRecommendation`. For example:
```

2020-12-10 15:18 UTC, OndraM commented on UPGRADE-4.0.md
> +Class `Sorting` was renamed to `ItemSorting`. All its methods and behaviour remained the same.
```suggestion
Class `Sorting` was renamed to `ItemSorting`. All its methods and behavior remained the same.
```
(also for consistency, dtto as in README)

2020-12-10 15:25 UTC, OndraM commented on README.md
> +| Atribute      | Methods                                   | UserItemRecommendation | UserUserRecommendation | ItemItemRecommendation | ItemUserRecommendation |
```suggestion
| Attribute      | Methods                                   | UserItemRecommendation | UserUserRecommendation | ItemItemRecommendation | ItemUserRecommendation |
```

2020-12-10 15:25 UTC, OndraM commented on UPGRADE-4.0.md
> +\* `UserMinimalRelevance` supports only `MEDIUM` and `HIGH` relevancies.
```suggestion
\* `UserMinimalRelevance` supports only `MEDIUM` and `HIGH` relevances.
```

Also this part is missing in the readme (so I suggest moving it to readme only).

2020-12-10 15:25 UTC, OndraM commented on UPGRADE-4.0.md
> +
```suggestion
```

2020-12-10 15:25 UTC, OndraM commented on UPGRADE-4.0.md
> +```
Missing end of line on the end of file

2020-12-16 10:30 UTC, JakubTesarek commented on README.md
> +You can also set more granular options of the recommendation command and overwrite Matej default behaviour on per-request basis.
fixed

2020-12-16 10:37 UTC, JakubTesarek commented on tests/unit/Model/Command/ItemItemRecommendationTest.php
> +        $this->assertSame(
Nah, I don't seem to be able to make it work with linter which doesn't like it. Also, I didn't modify the test, only the filename changed. I'm trying to keep the changes as minimal as possible.

2020-12-16 10:40 UTC, JakubTesarek commented on tests/unit/RequestBuilder/CampaignRequestBuilderTest.php
> +        $recommendationCommand4 = ItemItemRecommendation::create('itemId2', 'scenario3')
fixed

2020-12-16 11:33 UTC, OndraM requested changes

2020-12-16 11:33 UTC, OndraM commented on src/Model/Command/AbstractUserRecommendation.php
> +        if ($this->rotationRate !== null) {
🔝 This bug is still present (and few other comments as well)

2020-12-16 17:21 UTC, JakubTesarek commented on src/Model/Command/AbstractUserRecommendation.php
> +        if ($this->rotationRate !== null) {
The problem is that we don't have a test that would test parameters one by one. It didn't appear in coverage because 1) we have a test when rotationRate is set and 2) when it isn't so technically all branches were covered. But branch coverage is not enough in this case. I added test showing this particular bug was fixed but I don't plan to add a matrix test of all the combinations that are possible. It would be around 16M tests.

2020-12-17 13:22 UTC, merged