Add sorting command
lmc-eu/matej-client-php pull request #27
Opened 2017-11-23 16:34 UTC by foglcz

First part of #24 

The actual call to an endpoint is not part of this pull request - it will be implemented once all `Matej\Model\Commands` are present, as the individual calls can interfere with each other (and we can implement only after #20 is merged)

2017-11-23 18:45 UTC, jirinovak commented on src/Model/Command/Sorting.php
> +    public static function create(string $userId, array $itemIds): self
Add another named constructor `sortFor` or so?

Like `mergeInto` from #26 .

2017-11-23 18:45 UTC, jirinovak commented on src/Model/Command/Sorting.php
> +     * Sort given item ids for user-based recommendations
I think this is unnecessary as it is also in class comment. What do you think?

2017-11-23 19:29 UTC, OndraM requested changes

2017-11-23 19:29 UTC, OndraM commented on src/Model/Command/Sorting.php
> +        $this->userId = $userId;
In future, we may validate the values (and throw some exception on error) - like id length, format... I will create issue for that.

2017-11-23 19:29 UTC, OndraM commented on tests/Model/Command/SortingTest.php
> +     * @test
dtto, could be one line

2017-11-23 19:29 UTC, OndraM commented on src/Model/Command/Sorting.php
> +    public function __construct(string $userId, array $itemIds)
What about making it also private :)?

2017-11-23 19:29 UTC, OndraM commented on tests/Model/Command/SortingTest.php
> +class SortingTest extends TestCase
We extend "our" TestCase in other test... It has no added value right now, but we may do it here as well to make it unified.

2017-11-24 10:40 UTC, OndraM submitted a review, later dismissed

2017-11-24 10:47 UTC, jirinovak submitted a review, later dismissed

2017-11-25 20:21 UTC, merged