Add check for forbidden item_id in item properties (RAD-720)
lmc-eu/matej-client-php pull request #51
Opened 2017-12-04 12:36 UTC by foglcz

2017-12-04 13:48 UTC, OndraM requested changes

2017-12-04 13:48 UTC, OndraM commented on src/Model/Command/ItemProperty.php
> +        Assertion::keyNotExists(
I'd create protected setter for properties an put the assertion inside.

2017-12-04 13:49 UTC, OndraM commented
And what is the reason for this? Its because the item property name is there by default always?

And the item_id cannot be updated once item is created?

Maybe the reasons should be also explained in the exception message.

2017-12-04 14:47 UTC, foglcz commented
+ add chagnelog

2017-12-04 14:52 UTC, foglcz commented
Right. So, `item_id` is something like a primary key. In original tests:

```php
$ip = ItemProperty::create('exampleItemId', ['item_id' => 'someOtherItemId']);
echo $ip->getCommandParameters();
// ['item_id' => 'examleItemId']
```

While correct behaviour (property should not overwrite the id of the item), I felt that this would be confusing to the developer.

2017-12-05 10:33 UTC, OndraM requested changes

2017-12-05 10:33 UTC, OndraM commented on tests/Model/Command/ItemPropertyTest.php
> +    public function shouldNotAllowItemIdInProperties(): void
This should be placed after the following data provider

2017-12-05 10:33 UTC, OndraM commented on src/Model/Command/ItemProperty.php
> +            '$properties cannot contain key "item_id" - please use different key name.'
I'm not sure "please use different key name" is the best advice.

Maybe we should rather explain the item_id is already used for identifying the item and it cannot be updated.

2017-12-05 10:33 UTC, OndraM commented on src/Model/Command/ItemPropertySetup.php
> +        Assertion::notEq($propertyName, 'item_id', 'Cannot define property with name item_id - please use different name');
Dtto, maybe instead explain the item_id is set up in Matej by default and don't need to be set up explicitly.

2017-12-05 13:11 UTC, OndraM requested changes

2017-12-05 13:11 UTC, OndraM commented on tests/Model/Command/ItemPropertyTest.php
> +        $this->expectException(DomainException::class);
I'd add expectExceptionMessage - to make sure the exception occurred in the expected case.

2017-12-05 13:11 UTC, OndraM commented on src/Model/Command/ItemPropertySetup.php
> +            'Cannot redefine property item_id - it is used as primary key to identify items. Please use different name.'
`Cannot manipulate with property "item_id" - it is used by Matej to identify items.` or something?

2017-12-05 13:11 UTC, OndraM commented on src/Model/Command/ItemProperty.php
> +            '$properties cannot contain key item_id - it is used as primary key to identify the item. Please use different key instead.'
`Cannot update value of "item_id" property - it is used by Matej to identify the item and cannot be altered once created.` ?

2017-12-05 15:07 UTC, OndraM approved these changes

2017-12-05 15:14 UTC, merged