Add exception when merging same user ids (RAD-907)
lmc-eu/matej-client-php pull request #62
Opened 2018-01-26 09:46 UTC by foglcz

In near future, Matej API will stop accepting UserMerge requests, that cotain same user ids.

2018-01-26 11:25 UTC, jirinovak requested changes

2018-01-26 11:25 UTC, jirinovak commented on CHANGELOG.md
> +- Check for equality of user ids in `UserMerge` - so that we don't "merge" user into the same user id effectively deleting it.
Vincent said that deleting behaviour will be fixed. So maybe it is not necessary to mention it in docs. Hmm?

2018-01-29 13:01 UTC, OndraM requested changes

2018-01-29 13:01 UTC, OndraM commented on src/Model/Command/UserMerge.php
> +    public function jsonSerialize(): array
I'd not assert the values here. They should already be validated via custructor / setters.

2018-01-29 22:11 UTC, jirinovak approved these changes

2018-01-29 22:16 UTC, OndraM approved these changes

2018-01-31 21:53 UTC, merged