Implement A/B testing support for Recommendations and Sorting commands
lmc-eu/matej-client-php pull request #73
Opened 2018-04-13 13:44 UTC by foglcz

|  |  |
| --- | --- |
| **Type** | Feature |
| **Fixes issues** | RAD-1066 |
| **Documentation** | updated |
| **BC Break** | no |
| **Tests updated** | yes |

Contains implementation for A/B testing of various recommendation models. These models have to be implemented/deployed in Matej first, before they're available for any given client. This is by design, as new model requires full recalculation, and therefore availability is individual depending on the size of clients data.

By default, only `default` model is available for every client (which means *clients* default, not *matej* default.)

Requires **Matej release v7.36**
Currently deployed to Staging instance, which contains models `default` and `model_b`.

There is no API endpoint that'd list available models. No validation beyond basic identifier is required.

2018-04-16 16:16 UTC, OndraM requested changes

2018-04-16 16:16 UTC, OndraM commented on src/Model/Command/Sorting.php
> +        return $this;
We don't use fluent interfaces in this kind of setters.

2018-04-16 16:16 UTC, OndraM commented on README.md
> +If you don't provide any model name, the request will be sent without it, and matej will use default model for your instance.
*M*atej

2018-04-16 16:16 UTC, OndraM commented on README.md
> +$response =  $matej->request()
Two spaces before $matej (also five lines below)

2018-04-16 16:22 UTC, OndraM commented on README.md
> +$response = $matej->request()
You can try separating the commands to standalone variable - it could be more readable in comparison with those "oneliners".

2018-04-17 08:35 UTC, foglcz commented on src/Model/Command/Sorting.php
> +        return $this;
I thought we do? `Public` setters are generally fluent, `protected` setters are not.

I used `UserRecommendation` as code-style template https://github.com/lmc-eu/matej-client-php/blob/master/src/Model/Command/UserRecommendation.php#L103

2018-04-17 08:36 UTC, foglcz commented on README.md
> +If you don't provide any model name, the request will be sent without it, and matej will use default model for your instance.
Nice catch! :) :+1:

2018-04-17 08:36 UTC, foglcz commented on README.md
> +$response =  $matej->request()
:+1:

2018-04-17 08:36 UTC, foglcz commented on README.md
> +$response = $matej->request()
:+1:

2018-04-17 10:36 UTC, OndraM commented on src/Model/Command/Sorting.php
> +        return $this;
Sorry, my fault, I realized this later byt forgot to delete the comment :see_no_evil:

2018-04-17 13:08 UTC, OndraM approved these changes

2018-04-17 13:17 UTC, merged