Implement forget() builder for user data anonymization and/or deletion
lmc-eu/matej-client-php pull request #77
Opened 2018-05-29 12:08 UTC by foglcz

|  |  |
| --- | --- |
| **Type** | Feature |
| **Fixes issues** | RAD-1066 |
| **Documentation** | updated |
| **BC Break** | no |
| **Tests updated** | yes |

Implement new `forget()` endpoint, that exposes forgetting-functionality, effectively removing the manual GDPR process and enabling customers to implement the procedure in their codebase.

**Requires upcomming Matej v7.38**

2018-05-29 13:28 UTC, foglcz commented
Just did a final force push, the PR is ready for review. I've updated readme in the last force push:

*Alternative way is to `delete` the user, which will wipe their data from all databases ~~and logfiles~~ in accoardance`*

Logfiles are not cleared, but logrotated away in compliance with GDPR requirements. We just want to be clear about what's going on there 8-)

2018-05-30 07:29 UTC, kubasimon submitted a review, later dismissed

2018-05-30 07:29 UTC, tenerd commented on README.md
> +* Preffered way is to `anonymize` the user, which will generate a unique random identifiers for all personal data,
Preffered -> Preferred

2018-05-30 09:44 UTC, OndraM requested changes

2018-05-30 09:44 UTC, OndraM commented on README.md
> +Matej can "forget" user data, either by anonymizing or by deleting them. The right to forget is part of [data protection in the European Union](https://ec.europa.eu/info/law/law-topic/data-protection
Unnecessary comma after Union

2018-05-30 09:44 UTC, OndraM commented on README.md
> +* Preffered way is to `anonymize` the user, which will generate a unique random identifiers for all personal data,
Either "a unique identifier", or "unique identifiers"

2018-05-30 09:44 UTC, OndraM commented on README.md
> +  and change that identifier across all databases and logfiles. This way the users behaviour will stay in Matejs database,
"user's", "Matej's" (or rather just Matej, we use it this way elsewhere) :)

2018-05-30 09:44 UTC, OndraM commented on README.md
> +* Alternative way is to `delete` the user, which will wipe their data from all databases in accoardance
An alternative

2018-05-30 09:44 UTC, OndraM commented on README.md
> +* Alternative way is to `delete` the user, which will wipe their data from all databases in accoardance
accordance

2018-05-30 09:44 UTC, OndraM commented on README.md
> +  with the Data Protection laws. This may affect the quality of recommendations, as the users behaviour will be completely
behavior, to be consistent with other parts of readme

2018-05-30 09:44 UTC, OndraM commented on README.md
> +  removed from all databases, and therefore their profile will not contibute to the recommendation model anymore.
cont*r*ibute

2018-05-30 09:44 UTC, OndraM commented on README.md
> +Usually though, the user will identify whether they want their data anonymized or deleted, and you have to adhere to their request.
"Usually, though,"

2018-05-30 09:44 UTC, OndraM commented on README.md
> +
Unnecessary  newline?

2018-05-30 09:44 UTC, OndraM commented on README.md
> +
Unnecessary newline here as well?

2018-05-30 09:44 UTC, OndraM commented on src/Model/Command/ForgetUser.php
> +class ForgetUser extends AbstractCommand implements UserAwareInterface
We have "UserMerge" command, why this isn't UserForget?

2018-05-30 09:44 UTC, OndraM commented on src/Model/Command/ForgetUser.php
> +    const ANONYMIZE = 'anonymize';
Missing constant visibility

2018-05-30 09:44 UTC, OndraM commented on src/RequestBuilder/ForgetRequestBuilder.php
> +        if (empty($this->users)) {
This line should be divided (to adhere 120 chars per line limit)

2018-05-30 09:44 UTC, OndraM commented on src/RequestBuilder/ForgetRequestBuilder.php
> +            throw new LogicException('At least one user forget must be added to the builder before sending the request');
I would follow messages from other builders and use the command name:

"At least one ForgetUser command must be added to the builder before sending the request"

2018-05-30 09:44 UTC, OndraM commented on tests/unit/Model/Command/ForgetTest.php
> +class ForgetTest extends UnitTestCase
Test name should match "class under test name + Test", ie. ForgetUserTest or better UserForgetTest.

2018-05-30 09:49 UTC, OndraM commented on README.md
> +Matej can "forget" user data, either by anonymizing or by deleting them. The right to forget is part of [data protection in the European Union](https://ec.europa.eu/info/law/law-topic/data-protection
It is officially called "Right to erasure (‘right to be forgotten’)" https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32016R0679#d1e2606-1-1

So we should follow the same name for it.

2018-05-31 20:35 UTC, davidkmenta submitted a review, later dismissed

2018-05-31 21:31 UTC, OndraM requested changes
Just forgotten renaming :).

Also there is now a conflict in changelog (sorry, some change was merged in the meantime :) ), could you please resolve it?

2018-05-31 21:31 UTC, OndraM commented on src/RequestBuilder/ForgetRequestBuilder.php
> +                'At least one ForgetUser command must be added to the builder before sending the request'
Now with the renaming in effect it should be `UserForget` :)

2018-05-31 21:31 UTC, OndraM commented on README.md
> +    ->addUser(ForgetUser::anonymize('anonymize-this-user-id'))
Forgotten rename, should be `UserForget` (also on next lines)

2018-06-01 11:28 UTC, OndraM submitted a review, later dismissed

2018-06-01 11:52 UTC, OndraM approved these changes

2018-06-01 11:53 UTC, merged