Update docs: mention server-side rate-limiting
lmc-eu/matej-client-php pull request #79
Opened 2018-06-20 15:00 UTC by foglcz

Also updated in Matej documentation.

This feature is coming into Matej v7.39.

2018-06-26 19:39 UTC, OndraM requested changes

2018-06-26 19:39 UTC, OndraM commented on README.md
> +**This endpoint has rate-limiting implemnted.** We constantly monitor workload on backend systems,
implemented (typo)

2018-06-26 19:39 UTC, OndraM commented on README.md
> +and when the # of events in the queue crosses certain treshold, Matej API will start returning `503` errors.
threshold (typo)

2018-06-26 19:39 UTC, OndraM commented on README.md
> +and when the # of events in the queue crosses certain treshold, Matej API will start returning `503` errors.
I'd replace "#"  with "number" (for clarity)

2018-07-23 19:27 UTC, OndraM commented
Ping @foglcz ?

2018-07-24 09:17 UTC, foglcz commented
Fixed typos, thanks for the ping @OndraM :)

2018-07-24 15:18 UTC, OndraM approved these changes

2018-07-24 15:19 UTC, merged