Add support for allow_seen in Recommendation requests
lmc-eu/matej-client-php pull request #87
Opened 2018-09-13 13:06 UTC by foglcz

|  |  |
| --- | --- |
| **Type** | Feature |
| **Fixes issues** | RAD-1735 |
| **Requires Matej** | `>= 7.46.0` |
| **Documentation** | updated |
| **BC Break** | No |
| **Tests updated** | yes |
| **Notes** | n/a |

By default, "seen" is any item, that the user has DetailView'ed. This however, can be changed for any given model, so "seen" can mean different things in `default` and `gamma` model for any particular client.

2018-09-14 11:43 UTC, VincTheSecond submitted a review, later dismissed

2018-09-17 13:06 UTC, OndraM requested changes

2018-09-17 13:06 UTC, OndraM commented on CHANGELOG.md
> +- `UserRecommendation` can send `allow_seen`, which allows recommending of already visited items.
This (`allow_seen`) is from API point of view, maybe rather mention `setAllowSeen()` method from the API Client pow

2018-09-17 13:06 UTC, OndraM commented on src/Model/Command/UserRecommendation.php
> +     * By default user won't see any items, that he or she has visitted (and we have recorded DetailView interaction.)
`it has visited`

2018-09-17 13:06 UTC, OndraM commented on src/Model/Command/UserRecommendation.php
> +    public function setAllowSeen(bool $seen = true): self
This is confusing - we should either has setter `setAllowSeen(bool)` with **required** parameter, or two methods to set it to true and false (`allowSeen()` and eg. `disallowSeen()`). For simplicity I'd go for the first variant, but for sure not mix those two approaches.

2018-09-17 13:06 UTC, OndraM commented on src/Model/Command/UserRecommendation.php
> +        if ($this->allowSeen) {
Rather strict comparison (eg. `!== false`) instead of this truthy condition.

2018-09-18 11:42 UTC, OndraM approved these changes

2018-09-18 11:43 UTC, merged