Add new item property type geolocation
lmc-eu/matej-client-php pull request #89
Opened 2018-09-27 11:04 UTC by jirinovak

|  |  |
| --- | --- |
| **Type** | Feature |
| **Fixes issues** | RAD-1822 |
| **Requires Matej** | `>= 7.47.0` |
| **Documentation** | updated |
| **BC Break** | No |
| **Tests updated** | yes |
| **Notes** | n/a |

New item property type `geolocation` is required for using new operator `near` https://admin.matej.lmc.cz/docs/query_language.html#geolocation.

This item property is `composite` type. So question is if we should validate it's value?

2018-09-27 11:05 UTC, danger-lmc commented
<!--
  1 failure:  Backward incompat...
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-default;
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Backward incompatible changes detected
  </td>
    </tr>
  </tbody>
</table>




## Backward incompatible changes introduced by this PR
 - [BC] Value of constant Lmc\Matej\Matej::VERSION changed from '2.0.0' to '2.1.1'


<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

2018-09-27 11:13 UTC, OndraM requested changes
About the validation - the PHP client hasn't knowledge about data structure each user has in Matej. Thus when you setup item property as `set`, `timestamp`, `geolocation` etc., when updating its content, there is no way how to know against which Matej internal type the value should be validated. 

So you must build the request to match the internal type of the property you setup in Matej, the client cannot do the validation for you.

```
$matej->request()
    ->events()
    ->addItemProperty(
        ItemProperty::create('item-id', ['my_geolocation_field_but_client_do_not_know_the_type' => ['it', 'is', 'your' 'responsibility', 'to', 'provide', 'valid', 'data']])
    )
...
```

2018-09-27 11:13 UTC, OndraM commented on CHANGELOG.md
> +- New item property type `geolocation`
Please ass dot at the end of line

2018-10-01 16:18 UTC, merged

2018-10-01 16:18 UTC, OndraM commented
Thanks @jirinovak :tada: